name: Create Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major'
        required: true
        type: string
        default: '23.1'

  # release:
  #   types: published

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      release: ${{ steps.script.outputs.RELEASE }}
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3

      - name: Install packages
        run: npm ci
        working-directory: './.github/scripts'

      - name: Run script
        id: script
        run: node ./.github/scripts/analyse.mjs >> $GITHUB_OUTPUT
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAJOR: ${{ inputs.major }}
          BRANCH: ${{ github.ref_name }}

  job2:
    needs: job1
    uses: ./.github/workflows/on-release.yml
    with:
      release: ${{ needs.job1.outputs.release }}