name: On Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major'
        required: true
        type: string
        default: '23.1'

  # release:
  #   types: published

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout

      - name: Install node
        uses: actions/setup-node

      - name: Install packages
        run: npm ci
        working-directory: './.github/scripts'

      - name: Run script
        run: node ./.github/scripts/analyse.mjs
        env:
          REPO: ${{ github.repository }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAJOR: ${{ inputs.major }}