name: On release

on:
  release:
    types: [released, prereleased, deleted]
  workflow_call:

jobs:
  callBuild:
    runs-on: windows-latest
    steps:
      - name: Extract release
        id: extractRelease
        run: echo RELEASE=$([regex]::Match("${{ github.ref_name }}", "\d{2}\.\d").Groups[0].Value) >> $env:GITHUB_OUTPUT

      - name: Write vars
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ steps.extractRelease.outputs.RELEASE }}