name: On release

on:
  release:
    types: [released, prereleased, deleted]
  workflow_call:
    inputs:
      release:
        type: string
        required: false

jobs:
  callBuild:
    runs-on: windows-latest
    steps:
      - name: Extract release
        id: extractRelease
        run: |
          $str = ![string]::IsNullOrEmpty("${{ inputs.release }}") ? "${{ inputs.release }}" : [regex]::Match("${{ github.ref_name }}", "\d{2}\.\d").Groups[0].Value
          echo RELEASE=$str >> $env:GITHUB_OUTPUT

      - name: Write vars
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ steps.extractRelease.outputs.RELEASE }}